FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

ARG USERNAME=frappe
ARG USER_UID=1000
ARG USER_GID=1000

# Install system packages
RUN apt-get update && apt-get install -y \
    python-is-python3 python3-dev python3-pip python3-venv \
    redis-server libmariadb-dev mariadb-client pkg-config cron \
    xvfb libfontconfig tzdata \
    curl wget git sudo \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Node.js 18 + Yarn without NVM
RUN curl -fsSL https://deb.nodesource.com/setup_18.x | bash - && \
    apt-get install -y nodejs && \
    npm install -g yarn

# wkhtmltopdf with patched Qt
RUN wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6.1-2/wkhtmltox_0.12.6.1-2.jammy_arm64.deb && \
    apt install -y ./wkhtmltox_0.12.6.1-2.jammy_arm64.deb && \
    rm wkhtmltox_0.12.6.1-2.jammy_arm64.deb

# Install Bench
RUN pip3 install --upgrade pip && pip3 install frappe-bench

# Create frappe user
RUN useradd -ms /bin/bash -u $USER_UID $USERNAME && \
    usermod -aG sudo $USERNAME && \
    echo "$USERNAME ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

USER $USERNAME
WORKDIR /home/$USERNAME

